config/routes.rb
Rails.application.routes.draw do

    devise_for :users, controllers: { registrations: 'registrations' }

    resources :posts, only: [:index]

    authenticate :user do
        resources :posts, only: [:new, :create, :edit, :update, :destroy, :show] do
            resources :bids, only: [:new, :create, :index]
        end
        resources :users, only: [:show, :index, :edit, :update]
    end

    root to: 'posts#index'

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  delegate :email, to: :user, prefix: true
  delegate :name, to: :user, prefix: true
  belongs_to :post
  belongs_to :user
  validates_presence_of :amount
  validates_numericality_of :amount
  validates_presence_of :user_id
  validates_presence_of :post_id
  
  validate :bid_amount_value

  after_save :update_item
  after_destroy :update_item

  def self.most_recent
    order(:created_at).last
  end

  def update_item
      self.post.check_highest_bid
  end

  def bid_amount_value
      errors.add(:amount, "Must be higher than current bid") unless self.post.price < self.amount
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user    
    has_many :bids
    
    validates :user_id, presence: true
    validates :title, presence: {message: 'The auction must have a title'}
    validates :price, presence: {message: 'The item must have a starting price'}
    validates_numericality_of :price 
    validates_uniqueness_of :title
    validates :when_date, presence: {message: 'End date and time cannot be blank'}

    def check_highest_bid
        highest_bid = self.bids.order("amount DESC").first.amount rescue 0
        self.price = highest_bid
        save
    end

    enum status: {
        # The post is available for bids
        open: 0,
        # The post has one or more bids
        pending: 1,
        # More than 0 bids and the auction has end
        complete: 2,
        # No bids and the auction is over
        incomplete: 3
    }

    def update_status
        if pending? && when_date < DateTime.now
            # More than 0 bids and the auction has ended
            self.complete!
        elsif open? && when_date < DateTime.now  
            # 0 bids and the auction has ended
            self.incomplete!
        end
    end

    def is_auction_complete
        return self.status == 'complete'
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :bids
  has_many :posts
  # has_many :posts, through: :bids, :dependent => :destroy
  validates :email, presence: {message: 'You must enter your email'}
  validates :name, presence: { message: 'You must enter your name' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :set_bid, only: [:show, :edit]
  before_action :set_post, only: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  respond_to :html, :js

  def show
  end

  def index
      @bids = Bid.where(post_id: @post.id).order(:created_at)
  end

  def new
    @bid = Bid.new
  end

  def edit
  end

  def create 
      if current_user.id != @post.user_id
          if @post.open? || @post.pending?
              @bid = @post.bids.build(bid_params.merge(user_id: current_user.id))
              # Save the bid
              if @bid.save
                  flash[:notice] = 'Bid Placed'
                  # This logic should probably live in an activerecord callback
                  if @post.status == 'open'
                      @post.status = 'pending'
                      @post.save
                  end
              else
                  flash[:alert] = 'Bid NOT Placed'
              end
          else
              flash[:alert] = 'Not open for bidding'
          end
      else
          flash[:alert] = 'You cannot bid on your own auction'
      end
      redirect_to @post
  end

  private

  def set_bid
      @bid = Bid.find(params[:id])
  end

  def set_post
      @post = Post.find(params[:post_id])
  end

  def bid_params
      params.require(:bid).permit(:amount)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy, :bid]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html, :js

  def index
    if params[:query].present?
      @posts = Post.search(params[:query])
    else
      @posts = Post.all.order(created_at: :desc)
    end
  end

  def show
     @bid = Bid.new(:post=>@post)
     @most_recent_bid = Bid.joins(:post).where('post_id' => @post).order("created_at").last  
    # Shit don't work
    # @bid = @post.bids.build
    # @most_recent_bid = Bid.joins(:post).where(post_id: params[:id]).most_recent
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params.merge(user_id: current_user.id))
    # Save the post
    if @post.save
      flash[:notice] = 'Post Created'
      redirect_to posts_path
    else
      render :new
    end
  end

  def update
   @post.update(post_params)
   # @post.check_status 
   redirect_to post_path
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Post Deleted'
      redirect_to posts_path
    else
      render 'destroy'
    end

  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
      params.require(:post).permit(:title, :description, :price, :when_date)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
      #authorize!
      @users = User.all
    end

    # GET /users/:id.:format
    def show
      @user = User.find(params[:id])
      @user_posts = @user.posts.order(created_at: :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_error.html.erb
<% if resource.errors.any? %>
    <% resource.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
    <% end %>
<% end %>

app/views/bids/index.html.erb
<section class="main-content">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="page-sub-title textcenter">
					<h2>Bid History</h2>
					<div class="line"></div>
				</div><!-- end .page-sub-title -->
			</div>
			<%= render 'partials/bids' %>
		</div>
	</div>
</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'All Posts', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestScheduleableRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="container-fluid">
            <% if flash[:notice] %>
            <div class="alert-content">
                <div class="alert alert-success"><%= flash[:notice] %></div>
            </div>
            <% end %>
            <% if flash[:alert] %>
            <div class="alert-content">
                <div class="alert alert-danger"><%= flash[:alert] %></div>
            </div>
            <% end %>
	   <%= yield %>
        </div>
</body>
</html>

app/views/partials/_bids.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Something big</h1>
    <p><%= link_to "Sign Up To Bid", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>
<% if @bids.exists? %>
  <div class="col-sm-6 col-md-3">
    <% @bids.each do |bid| %>
      <div class="row-sm-6 row-md-3">
          <%= link_to bid.user.name, user_path(bid.user.id) %> <%= bid.amount %> <%= bid.created_at.strftime("%Y-%m-%d %H:%M") %></h3>
      </div>
    <% end %>
  </div>
<% else %>
<div class="col-xs-12">
    <article class="ride-box clearfix">
        <div class="ride-content">
            <h3>No bids yet</h3>
        </div>
    </article>
</div>
<% end %>

app/views/partials/_posts.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Auctions Everywhere</h1>
    <p><%= link_to "Sign Up To Bid", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>
<% if @posts.exists? %>
  <div class="row">
    <% @posts.each do |post| %>
        <div class="col-sm-6 col-md-3">
            <p><%= link_to post.title, post_path(post) %> by <%= post.user.email %></p>
        </div>
    <% end %>
  </div>
<% else %>
    <div class="col-xs-12">
        <article class="ride-box clearfix">
        <div class="ride-content">
            <h3>No posts yet</h3>
        </div>
        </article>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
<%= render 'form_error', resource: f.object %>
<div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</div>
<div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</div>
<div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
</div>
<div class="field">
    <%= f.label :when_date %><br>
    <%= f.datetime_local_field :when_date %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/posts/_partials.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Something big</h1>
    <p><%= link_to "Sign Up To Bid", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>
<% if @posts.exists? %>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-sm-6 col-md-3">
          <%= link_to post.title, post_path(post) %> by <%= post.user.email %></h3>
      </div>
    <% end %>
  </div>
<% else %>
<div class="col-xs-12">
    <article class="ride-box clearfix">
        <div class="ride-content">
            <h3>No posts yet</h3>
        </div>
    </article>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="main-content">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="page-sub-title textcenter">
					<h2>All Posts</h2>
					<div class="line"></div>
				</div><!-- end .page-sub-title -->
			</div>
			<%= render 'partials/posts' %>
		</div>
	</div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                            <tr>
                                <td><strong>Title:</strong></td>
                                <td><%= @post.title %></td>
                            </tr>
                            <tr>
                                <td><strong>Posted By:</strong></td>
                                <td><%= link_to (@post.user.name), user_path(@post.user) %></td>
                            </tr>
                            <tr>
                                <td><strong>Description:</strong></td>
                                <td><%= @post.description %></td>
                            </tr>
                            <tr>
                                <td><strong>Expiration Date:</strong></td>
                                <td><%= @post.when_date.strftime("%Y-%m-%d %H:%M") %></td>
                            </tr>
                            <tr>
                                <td><strong>Status:</strong></td>
                                <td><%= @post.status %></td>
                            </tr>
                            <tr>
                                <td><strong>Price:</strong></td>
                                <% if @post.bids.present? %>
                                    <td><%= @most_recent_bid.amount %> </td>
                                  <% else %>
                                    <td><%= @post.price %></td>
                                <% end %>
                            </tr>
                            <tr>
                                <td><strong>Number of bids:</strong></td>
                                <td><%= link_to (@post.bids.count), post_bids_path(@post) %></td>
                            </tr>
                        </tbody>
                    </table>
                    <% if @post.status == 'incomplete' %>
                        <h3>Item NOT sold</h3>
                    <% end %>
                    <% if @post.status == 'complete' %>
                        <h3>Sold</h3>
                    <% end %>
                    <% if @post.status == 'open' || @post.status == 'pending' %>

                            <%= form_for [@post, @bid] do |f| %>
                                <%= render 'form_error', resource: f.object %>
                                <%= f.label(:amount, "Amount:") %>
                                <%= f.number_field(:amount) %>
                                <%= f.submit("Submit") %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>
</div>
<% if @post.user_id == current_user.id %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', post_path(@post), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
<%= link_to 'Back', posts_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>Contact me at: <%= @user.email %></p>

<% if @user_posts.exists? %>
    <h3><%= @user.name %>'s Posts</h3>
    <% @user_posts.each do |post| %>
        <p><%= link_to post.title, post_path(post) %></p>
    <% end %>
<% else %>
    <p>Sorry, I haven't sold anything yet</p>
<% end %>